- id: '1536096958287'
  alias: Hallway light on
  trigger:
  - entity_id: sensor.aeotec_zw100_multisensor_6_burglar_2
    from: '0'
    platform: state
    to: '8'
  action:
  - alias: ''
    data:
      entity_id: light.hallway_light
    service: light.turn_on
- id: '1536097422923'
  alias: Hallway light off
  trigger:
  - entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor_2
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.hallway_light
    service: light.turn_off
- id: '1536098245764'
  alias: Kitchen light on
  trigger:
  - entity_id: sensor.aeotec_zw100_multisensor_6_burglar
    from: '0'
    platform: state
    to: '8'
  condition: []
  action:
  - data:
      entity_id: light.kitchen_led
    service: light.turn_on
- id: '1536098361449'
  alias: Kitchen light off
  trigger:
  - entity_id: sensor.aeotec_zw100_multisensor_6_burglar
    from: '8'
    platform: state
    to: '0'
  condition: []
  action:
  - data:
      entity_id: light.kitchen
    service: light.turn_off
- id: '1537717047699'
  alias: Heal Components Nightly
  trigger:
  - at: '2:31:00'
    platform: time
  condition: []
  action:
  - service: zwave.heal_network
- id: '1545421313210'
  alias: Garage light on
  trigger:
  - entity_id: sensor.aeotec_zw100_multisensor_6_burglar_4
    from: '0'
    platform: state
    to: '8'
  condition: []
  action:
  - data:
      entity_id: switch.garage_light
    service: switch.turn_on
  - data:
      message: Motion in the garage
    service: notify.lametric
  - data:
      message: Motion in the garage. Light turned on.
    service: notify.telegramnotify
- id: '1545421397370'
  alias: Garage light off
  trigger:
  - entity_id: sensor.aeotec_zw100_multisensor_6_burglar_4
    from: '8'
    platform: state
    to: '0'
  condition: []
  action:
  - data:
      entity_id: switch.garage_light
    service: switch.turn_off
  - data:
      message: Garage light turned off.
    service: notify.telegramnotify
- id: '1551313242589'
  alias: HARestart
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      message: Homeassistant has been restarted
    service: notify.lametric
  - data:
      message: Homeassistant has been restarted
    service: notify.html5
  - data:
      message: Homeassistant has been restarted
    service: notify.slack
- id: '1551820996619'
  alias: Front Door Opened
  trigger:
  - entity_id: sensor.aeotec_zw120_door_window_sensor_gen5_access_control
    from: '23'
    platform: state
    to: '22'
  condition: []
  action:
  - data:
      message: Front Door has been opened
    service: notify.lametric
  - data:
      message: Front Door has been opened
    service: notify.telegramnotify
