- platform: tplink
  name: Garage Light
  enable_leds: true
  host: 192.168.1.59

- platform: tplink
  name: Boys Room TV
  enable_leds: true
  host: 192.168.1.196


- platform: rest
  resource: http://192.168.1.200:8126/container/letsencrypt
  name: Lets Encrypt
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
 
