# Lights
- platform: template
  sensors: 
    number_of_lights_on: 
      value_template: >-
        {{ states.light
           | selectattr('state', 'eq', 'on')
           | rejectattr('attributes.is_hue_group')
           | list
           | count
        }}
