- platform: darksky
  api_key: !secret darksky_key
    
  monitored_conditions:
    - summary
    - precip_type
    - precip_intensity
    - temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - nearest_storm_distance
    - minutely_summary
    - hourly_summary
    - daily_summary
    - pressure
    - visibility

