- platform: mold_indicator
  name: Living Room Mold
  indoor_temp_sensor: sensor.netatmo_wwc_indoor_temperature
  indoor_humidity_sensor: sensor.downstairs_thermostat_humidity
  outdoor_temp_sensor: sensor.netatmo_wwc_outside_temperature
  calibration_factor: 11.8

- platform: mold_indicator
  name: Bathroom Mold
  indoor_temp_sensor: sensor.aeotec_zw100_multisensor_6_temperature_3
  indoor_humidity_sensor: sensor.aeotec_zw100_multisensor_6_relative_humidity_3
  outdoor_temp_sensor: sensor.netatmo_wwc_outside_temperature
  calibration_factor: 11.8

