- alias: Bathroom light on
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_burglar_3
      from: '0'
      to: '8'
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 3.5
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Bathroom"
        scene_name: "Nightlight"

- alias: Bathroom light off
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_burglar_3
      from: '8'
      to: '0'
  action:
    - service: light.turn_off
      entity_id: light.hue_color_spot_1
    - service: light.turn_off
      entity_id: light.hue_color_spot_2
    - service: light.turn_off
      entity_id: light.hue_color_spot_3
    - service: light.turn_off
      entity_id: light.hue_color_spot_4
      


