- alias: Front Door Opened
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: sensor.aeotec_zw120_door_window_sensor_gen5_access_control
    from: '23'
    to: '22'
  action:
    - service: notify.lametric_alert
      data:
        message: Front Door has been opened
    - service: notify.telegramnotify
      data:
       message: Front Door has been opened

