- alias: 'Garage light on'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_burglar_4
      from: '0'
      to: '8'
  action:
    - service: switch.turn_on
      entity_id: switch.garage_light
    - service: notify.lametric_alert
      data:
        message: Motion in the garage!
    - service: notify.telegramnotify
      data:
        message: Motion in the garage!


- alias: 'Garage  light off'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor
      from: '8'
      to: '0'
  action:
    - service: switch.turn_off
      entity_id: switch.garage_light



