- alias: Hallway light on
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zwa005_trisensor_burglar
      from: '0'
      to: '8'
  action:
    - service: light.turn_on
      entity_id: light.hallway_light

- alias: Hallway light off
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zwa005_trisensor_burglar
      from: '8'
      to: '0'
  action:
    - service: light.turn_off
      entity_id: light.hallway_light


