- alias: Home Assistant Restarted
  initial_state: 'on'
  trigger:
    - event: start
      platform: homeassistant
  action:
    - service: notify.lametric
      data:
        message: Home Assistant has been restarted
    - service: notify.telegramnotify
      data:
        message: Home Assistant has been restarted

