- alias: 'Kitchen light on'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_burglar
      from: '0'
      to: '8'
  action:
    - service: light.turn_on
      entity_id: light.kitchen

- alias: 'Kitchen light off'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor
      from: '8'
      to: '0'
  action:
    - service: light.turn_off
      entity_id: light.kitchen


