- alias: Landing light on
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_burglar_6
      from: '0'
      to: '8'
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 3.5
  action:
    - service: light.turn_on
      entity_id: light.landing_light

- alias: Landing light off
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.aeotec_zw100_multisensor_6_burglar_6
      from: '8'
      to: '0'
  action:
    - service: light.turn_off
      entity_id: light.landing_light
      


